const font = {
  xxxs: '8px',
  xxs: '9px',
  xs: '10px',
  s: '13px',
  m: '16px',
  l: '18px',
  xl: '22px',
  xxl: '28px',
  xxxl: '36px',
  xxxxl: '48px',
  xxxxxl: '64px',
  xxxxxxl: '96px',
  mobile: {
    xxxs: '7px',
    xxs: '8px',
    xs: '9px',
    s: '10px',
    m: '12px',
    l: '14px',
    xl: '16px',
    xxl: '20px',
    xxxl: '25px',
    xxxxl: '30px',
    xxxxxl: '40px',
    xxxxxxl: '60px',
  },
};

export default font;
